Updated README
degica/rails_pages pull request #17
Opened 2022-10-04 07:29 UTC by Agroang

For the KOMOJU Card project we have been implementing the use of `pages` and while doing so we faced some challenges. 
For example the use of Composition & Options API, the initial setup, among others.

This PR just updates the README file to try to make it easier if you have never used the gem.

2022-10-04 07:31 UTC, degicat commented
@Resonious can you help us review this PR, please?

2022-10-05 04:41 UTC, Resonious requested changes
Thanks! These are great additions. I'd just like to make the code examples look nicer with syntax highlighting.

2022-10-05 04:41 UTC, Resonious commented on README.md
> +# app/pages/my_page/page.rb
Syntax highlighting :wink: 
```suggestion
```ruby
# app/pages/my_page/page.rb
```

2022-10-05 04:41 UTC, Resonious commented on README.md
> +# app/pages/my_page/page.vue
```suggestion
```javascript
// app/pages/my_page/page.vue
```

2022-10-05 07:57 UTC, merged